version: '3'
services:
  parser:
    restart: always
    build:
      context: .
      dockerfile: parser/Dockerfile
    environment:
      RESTART_TIME: 5
    network_mode: "host"
    volumes:
      - ./parser/data:/app/data
    logging:
      driver: "none"
    deploy:
      resources:
        limits:
          cpus: '3.0'       # Максимум 2 CPU
          memory: 6G        # Максимум 4 ГБ памяти
        reservations:
          cpus: '2.0'       # Минимум 1 CPU
          memory: 4G        # Минимум 2 ГБ памяти

volumes:
  data: