version: '3'
services:
  parser:
    restart: always
    build:
      context: .
      dockerfile: parser/Dockerfile
    environment:
      RESTART_TIME: 5
    network_mode: "host"
    volumes:
      - /data:/data